const queryString = require('query-string');
const Constants = require('./Constants');

module.exports = ({
  viewType = Constants.VIEW_TYPE_LIST,
  channel = Constants.CHANNEL_TYPE_BUY,
  minBedrooms = 1,
  maxBedrooms = null,
  maxPrice = null,
  minPrice = null,
  numberOfPropertiesPerPage = 499,
  radius = Constants.RADIUS_1,
  propertyTypes = [
    Constants.PROPERTY_TYPE_DETACHED,
    Constants.PROPERTY_TYPE_SEMIDETACHED,
    Constants.PROPERTY_TYPE_TERRACED,
    Constants.PROPERTY_TYPE_BUNGALOW,
  ],
  dontShow = [Constants.DONT_SHOW_RETIREMENT, Constants.DONT_SHOW_SHARED],
  primaryDisplayPropertyType = 'houses',
  includeSSTC = false,
  // isFetching = false,
  areaSizeUnit = Constants.AREA_SIZE_SQFT,
  sortType = Constants.SORT_TYPE_NEWEST,
} = {}) => queryString.stringify({
  viewType,
  channel,
  minBedrooms,
  maxBedrooms,
  maxPrice,
  minPrice,
  numberOfPropertiesPerPage,
  radius,
  propertyTypes: propertyTypes.join(','),
  dontShow: dontShow.join(','),
  primaryDisplayPropertyType,
  includeSSTC,
  // isFetching,
  areaSizeUnit,
  sortType,
});
